name: Tuist - Build and Analyze
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build and analyse default scheme using tuist command
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tuist build
        uses: tuist/tuist-action@0.13.0
        with:
          command: build
          arguments: ""
