name: Tuist - Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Test default scheme using tuist command
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            Tuist/Dependencies
          key: ${{ runner.os }}-tuist-${{ hashFiles('Tuist/Dependencies/graph.json') }}
          restore-keys: |
            ${{ runner.os }}-tuist-
      - name: Tuist fetch
        uses: tuist/tuist-action@0.13.0
        with:
          command: fetch
      - name: Tuist test
        uses: tuist/tuist-action@0.13.0
        with:
          command: test
